Data source: https://www.kaggle.com/fivethirtyeight/fivethirtyeight-bachelorette-dataset?select=bachelorette.csv

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [4]:
df = pd.DataFrame(pd.read_csv('../resources/bachelorette.csv'))
df

,SHOW,SEASON,CONTESTANT,ELIMINATION-1,ELIMINATION-2,ELIMINATION-3,ELIMINATION-4,ELIMINATION-5,ELIMINATION-6,ELIMINATION-7,...,DATES-1,DATES-2,DATES-3,DATES-4,DATES-5,DATES-6,DATES-7,DATES-8,DATES-9,DATES-10
0,SHOW,SEASON,ID,1,2,3,4,5,6,7,...,1,2,3,4,5,6,7,8,9,10
1,Bachelorette,13,13_BRYAN_A,R1,NaN,NaN,R,R,NaN,R,...,NaN,NaN,D6,D13,D1,D7,D1,D1,D1,D1
2,Bachelorette,13,13_PETER_K,NaN,R,NaN,NaN,NaN,R,R,...,NaN,D1,D6,D13,D9,D7,D1,D1,D1,D1
3,Bachelorette,13,13_ERIC_B,NaN,NaN,R,NaN,NaN,R,R,...,NaN,D10,D8,D13,D9,D1,D3,D1,D1,NaN
4,Bachelorette,13,13_DEAN_U,NaN,R,NaN,R,NaN,NaN,R,...,NaN,D8,D8,D1,D9,D7,D1,D1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
916,Bachelor,01,01_KRISTINA_X,E,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
917,Bachelor,01,01_LISA_X,E,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
918,Bachelor,01,01_PAULA_X,E,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
919,Bachelor,01,01_RACHEL_X,E,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
920,Bachelor,01,01_WENDI_X,E,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
bachelorette_r1 = df.loc[(df['ELIMINATION-1']=='R1') & (df['SHOW']=='Bachelorette')]
bachelor_r1 = df.loc[(df['ELIMINATION-1']=='R1') & (df['SHOW']=='Bachelor')]

bachelorette_winner = df.loc[df['SHOW']=='Bachelorette'].groupby('SEASON').first()
bachelor_winner = df.loc[df['SHOW']=='Bachelor'].groupby('SEASON').first()
bachelor_winner

,SHOW,CONTESTANT,ELIMINATION-1,ELIMINATION-2,ELIMINATION-3,ELIMINATION-4,ELIMINATION-5,ELIMINATION-6,ELIMINATION-7,ELIMINATION-8,...,DATES-1,DATES-2,DATES-3,DATES-4,DATES-5,DATES-6,DATES-7,DATES-8,DATES-9,DATES-10
SEASON,,,,,,,,,,,,,,,,,,,,,
01,Bachelor,01_AMANDA_M,E,E,E,E,E,W,NaN,NaN,...,NaN,D5,D1,D1,D1,D1,NaN,NaN,NaN,NaN
02,Bachelor,02_HELENE_E,E,E,E,E,E,E,W,NaN,...,NaN,D5,D1,D1,D1,D1,D1,NaN,NaN,NaN
03,Bachelor,03_JEN_X,E,E,E,E,E,E,W,NaN,...,NaN,D5,D5,D1,D1,D1,D1,NaN,NaN,NaN
04,Bachelor,04_Kelly-Jo,E,ED,E,E,E,E,E,NaN,...,NaN,D4,D3,D1,D1,D1,D1,NaN,NaN,NaN
05,Bachelor,05_JESSICA_B,R1,E,E,E,E,E,W,NaN,...,NaN,D7,D6,D1,D1,D1,D1,NaN,NaN,NaN
06,Bachelor,06_Mary,E,E,E,E,E,E,E,W,...,NaN,D1,D2,D1,D1,D1,D1,D1,NaN,NaN
07,Bachelor,07_Sarah B.,R,R,R,R,E,E,W,NaN,...,D9,D10,D6,D1,D1,D1,D1,NaN,NaN,NaN
08,Bachelor,08_Sarah_S,E,R,R,R,E,E,W,NaN,...,NaN,D12,D5,D1,D1,D1,D1,NaN,NaN,NaN
09,Bachelor,09_JENNIFER_W,R1,R,R,R,E,E,W,NaN,...,NaN,D6,D6,D1,D1,D1,D1,NaN,NaN,NaN
10,Bachelor,10_TESSA_H,R1,R,R,R,E,E,E,W,...,NaN,D7,D2,D4,D1,D1,D1,D1,NaN,NaN
11,Bachelor,11_DEANNA_P,R1,R,R,R,E,E,E,E,...,NaN,D7,D6,D2,D4,D1,D1,D1,NaN,NaN
12,Bachelor,12_SHAYNE_L,R1,R,R,R,E,E,E,W,...,NaN,D7,D1,D6,D4,D1,D1,D1,NaN,NaN
13,Bachelor,13_MELISSA_R,R,R,R,R,E,E,E,W,...,NaN,D1,D8,D6,D1,D1,D1,D1,NaN,NaN
14,Bachelor,14_VIENNA_G,R1,R,R,R,E,E,EQ,W,...,NaN,D5,D1,D6,D2,D1,D1,D1,NaN,NaN
15,Bachelor,15_EMILY_M,R1,R,R,R,R,R,R,E,...,NaN,D15,D1,D1,D8,D6,D1,D1,D1,D1
16,Bachelor,16_COURTNEY_R,R1,R,R,R,R,R,R,E,...,NaN,D1,D1,D8,D9,D6,D1,D1,D1,D1
17,Bachelor,17_CATHERINE_G,R1,R,R,R,R,R,R,E,...,NaN,D13,D12,D8,D8,D1,D3,D1,D1,D1
18,Bachelor,18_NIKKI_F,R1,R,R,R,R,R,R,E,...,NaN,D13,D10,D6,D1,D6,D1,D1,D1,D1
19,Bachelor,19_WHITNEY_B,R1,R,R,R,R,R,R,E,...,NaN,D11,D1,D6,D9,D6,D1,D1,D1,D1
20,Bachelor,20_LAUREN_B,R1,R,R,R,R,R,R,E,...,NaN,D10,D1,D12,D9,D7,D1,D1,D1,D1
21,Bachelor,21_VANESSA_G,R1,R,R,R,R,R,R,E,...,NaN,D12,D1,D13,D10,D6,D1,D1,D1,D1
SEASON,Bachelor,ID,1,2,3,4,5,6,7,8,...,1,2,3,4,5,6,7,8,9,10